---
- hosts: all
  tasks: 
   - name: creating a folder
     win_file:
      path: C:\Temp\
      state: directory
    
   - name: Download file from a file path
     get_url:
      url: https://github.com/srikanthbanala/towerTestWeb/tree/master/towerweb.htm
      dest: C:\Temp\towerweb.htm
      
