---
- hosts: all
  tasks: 
   - name: creating a folder
     win_file:
      path: C:\Temp\
      state: directory
    
   - name: create a file in the folder
     win_file:
       path: C:\Temp\new.txt
       state: touch
