---
- name: creating a folder
  win_file:
    path: C:\Temp\
    state: directory
    #just a comment updated
- debug:
    var: vault_var
    verbosity: 2
- name: create a file in the folder
  win_file:
     path: C:\Temp\new.txt
     state: touch
