---
- name: creating a folder
  win_file:
    path: C:\Temp\
    state: directory
    #just a comment updated
- debug:
    msg: "this is the password found {{ vault_var }}"
    verbosity: 2
- name: create a file in the folder
  win_file:
     path: C:\Temp\{{ vault_var }}.txt
     state: touch
